#!/snap/bin/node

let urllib = require("urllib");
let Phrase = require("zaschiff-palindrome");
let url = 'https://cdn.learnenough.com/phrases.txt';

urllib.request(url, { followRedirect: true }, function(error, data, repsonse) {
    let body = data.toString();
    let lines = body.split("\n");
    let palindromes = lines.filter(line => new Phrase(line).palindrome());
    palindromes.forEach(function(palindrome) {
        console.log("palindrome detected:", palindrome);
    })

})